### PR TITLE
Add scripts to bootstrap before running docker-compose

### LINKED ISSUE #48: No acces to goalie-js when building niceday-broker with docker
When  running the niceday-broker container we try to install goalie-js, but we don't have access to it's private github repo. We get the following error.
```
niceday-broker_1  | npm WARN niceday-router@0.1.0 No repository field.
niceday-broker_1  |
niceday-broker_1  | npm ERR! Error while executing:
niceday-broker_1  | npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/senseobservationsystems/goalie-js.git
niceday-broker_1  | npm ERR!
niceday-broker_1  | npm ERR! Host key verification failed.
niceday-broker_1  | npm ERR! fatal: Could not read from remote repository.
niceday-broker_1  | npm ERR!
niceday-broker_1  | npm ERR! Please make sure you have the correct access rights
niceday-broker_1  | npm ERR! and the repository exists.
niceday-broker_1  | npm ERR!
niceday-broker_1  | npm ERR! exited with error code: 128
```
There is 2 possible solutions:
- Make the goalie-js a subrepo of this repository (not sure if that works)
- Make a build script that checks out the repo, and afterwards builds the docker image.

### PR DESCRIPTION
**Pull request by svenvanderburg**
Fixes #48 by cloning  `goalie-js` repo before building the node.js docker image, for both `niceday-api` and `niceday-broker`. 

I followed conventions from https://github.com/github/scripts-to-rule-them-all .

I think this is not yet an optimal solution, it makes running the application a bit more complicated, but things will improve once we do #73 

@reviewer please see if the instructions make sense and whether you can succesfully run them!

### CODE REVIEW

**Comment by raar1** [comment]
I think I'm doing something wrong, but when I run
```
./script/server
```
from the repo root dir I still get the error I saw before e.g.
```
niceday-broker_1  | npm ERR! Error while executing:
niceday-broker_1  | npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/senseobservationsystems/goalie-js.git
niceday-broker_1  | npm ERR!
niceday-broker_1  | npm ERR! Host key verification failed.
niceday-broker_1  | npm ERR! fatal: Could not read from remote repository.
```

The `niceday-broker/script/bootstrap` is running without errors. If I try building the niceday-broker myself (with `docker build` then that also completes without any issues). But when the container runs I get the above error which looks like it's still trying to go fetch it (on my system, at least)

**Comment by raar1** [comment]
Should something like `package.json` or the lock file be telling `npm` not to try fetching it? They do appear to be being copied into the container correctly, so not sure what's wrong.

**Comment by svenvanderburg** [comment]
Can you try:
```
./script/server
docker-compose up  --build --force-recreate
```
If that works, probably you are still using old docker images.
Maybe we should update `./script/server` so we do this by default, I think currently most users (i.e. us) expect the docker images to be rebuild.

**Comment by raar1** [comment]
OK I tried with the `--force-recreate` etc but I still get the same errors. I'm assuming this just works fine on your machine?

Not sure if it's relevant, but I get the following warning:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

And also about a thousand warnings that look like the following:
```
npm WARN tar ENOENT: no such file or directory, open '/app/node_modules/.staging/import-local-99513249/package.json'
```

Do you get these warnings too?

This warning also looks suspicious:
```
niceday-broker_1  | npm WARN niceday-router@0.1.0 No repository field.
```

**Comment by svenvanderburg** [comment]
@raar1 I now use the git clone approach instead of depending on the local machine's npm. Can you try again?

**Comment by raar1** [comment]
OK so I was getting a permission denied when git cloning from `git@github.com:senseobservationsystems/goalie-js.git` but so I changed it to use the https url instead. I also made the bootstrap scripts fail early if the cloning fails.

The niceday-broker now seems to build but when it runs I get this warning:
```
niceday-broker_1  | (node:32) UnhandledPromiseRejectionWarning: Error
niceday-broker_1  |     at ChatNotAuthorizedError.SenseError [as constructor] (/app/node_modules/@sense-os/error/index.js:10:19)
niceday-broker_1  |     at new ChatNotAuthorizedError (/app/build/goalie-js/dist/commons/Error.js:32:42)
niceday-broker_1  |     at Object.wrapToChatError (/app/build/goalie-js/dist/chat/error.js:7:16)
niceday-broker_1  |     at resetConnectionIfConnectionError (/app/build/goalie-js/dist/chat/client/connection.js:27:19)
niceday-broker_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
niceday-broker_1  | (Use `node --trace-warnings ...` to show where the warning was created)
niceday-broker_1  | (node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
niceday-broker_1  | (node:32) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I logged in again and used a fresh token but I still see this warning. Was that already there before?

**Comment by svenvanderburg** [comment]
Hmmm, that is strange...
1. I get ` remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.` if I use https. How does this still work on your system? And ssh should just work right? Seems like something is wrong in your ssh/git authentication setup? Or can you clone other repos?
2. I also get the `ChatNotAuthorizedError` error, also with a fresh token... I will investigate it on wednesday. Or you can pick this issue up if you want.

**Comment by raar1** [comment]
>     1. I get ` remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.` if I use https. How does this still work on your system? And ssh should just work right? Seems like something is wrong in your ssh/git authentication setup? Or can you clone other repos?

Yes this is strange... it probably is a problem with my git config then. I'll look into that.

**Comment by raar1** [comment]
Right there indeed was something weird with my ssh keys. I've returned the git clone command to use ssh again.

If I get through my current issues I might have time to look into the `ChatNotAuthorizedError`

**Pull request merged**
