### PR TITLE
Refactor rasa action server docker-related files.

### PR DESCRIPTION
**Pull request by svenvanderburg**
* Move actions server Dockerfile back to Rasa_Bot root
* Rename Rasa_Bot/actions/requirements.txt -> Rasa_Bot/actions/requirements-actions.txt
* Update README accordingly

### CODE REVIEW

**Comment by nelealbers** [comment]
@svenvanderburg  What did the commit "undo changes to rasa database" do?

**Comment by svenvanderburg** [comment]
> @svenvanderburg What did the commit "undo changes to rasa database" do?

I accidentally committed changes to `rasa.db`, which I didn't want to. So I reverted it, sorry if the commit message is a bit too cryptic ;)

**Comment by svenvanderburg** [comment]
@nelealbers was that your only comment and can I go ahead with the merge?

**Comment by nelealbers** [comment]
@svenvanderburg Yes, that was all - just did not know what that secret commit was supposed to do :D.

**Pull request merged**
